# Generated by Django 5.2.15 on 2026-08-05 18:27
#
# Faculty/Department moved to apps.home.models 2026-08-06 (see that app's
# 0001_initial.py) -- academic/institutional structure, not staff-specific.
# Employee.department is added back in 0002_initial as a cross-app FK to
# 'home.department', once home's migration 0001 (which creates it) has run.

import apps.staff.models
import autoslug.fields
import django.core.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('level', models.PositiveSmallIntegerField(default=5, help_text='Seniority rank: 5 (most junior) – 15 (most senior)', validators=[django.core.validators.MinValueValidator(5), django.core.validators.MaxValueValidator(15)])),
            ],
            options={
                'verbose_name': 'Position',
                'verbose_name_plural': 'Positions',
                'ordering': ['-level', 'title'],
            },
        ),
        migrations.CreateModel(
            name='ResearchUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of institute or research centre', max_length=255, unique=True, verbose_name='Research Unit Name')),
                ('slug', autoslug.fields.AutoSlugField(always_update=True, blank=True, editable=True, null=True, populate_from='name', unique=True, verbose_name='Slug')),
                ('description', models.TextField(blank=True, null=True)),
                ('unit_type', models.CharField(blank=True, choices=[('INSTITUTE', 'Institute'), ('CENTRE', 'Centre')], max_length=20, null=True, verbose_name='Unit Type')),
            ],
            options={
                'verbose_name': 'Research Unit',
                'verbose_name_plural': 'Research Units',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ServiceUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of office, directorate, or administrative unit', max_length=255, unique=True, verbose_name='Service Unit Name')),
                ('slug', autoslug.fields.AutoSlugField(always_update=True, blank=True, editable=True, null=True, populate_from='name', unique=True, verbose_name='Slug')),
                ('description', models.TextField(blank=True, null=True)),
                ('unit_type', models.CharField(blank=True, choices=[('OFFICE', 'Office'), ('DIRECTORATE', 'Directorate'), ('BOARD', 'Board'), ('CENTRE', 'Centre'), ('OTHER', 'Other')], max_length=50, null=True, verbose_name='Unit Type')),
            ],
            options={
                'verbose_name': 'Service Unit',
                'verbose_name_plural': 'Service Units',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('staff_id', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Staff ID')),
                ('academic_rank', models.CharField(blank=True, choices=[('graduate_assistant', 'Graduate Assistant'), ('tutorial_fellow', 'Tutorial Fellow'), ('lecturer', 'Lecturer'), ('senior_lecturer', 'Senior Lecturer'), ('associate_professor', 'Associate Professor'), ('professor', 'Professor'), ('research_fellow', 'Research Fellow'), ('senior_research_fellow', 'Senior Research Fellow'), ('research_professor', 'Research Professor')], default='', help_text='Formal academic rank: Lecturer, Senior Lecturer, Associate Professor, Professor, etc.', max_length=50, verbose_name='Academic Rank')),
                ('staff_track', models.CharField(blank=True, choices=[('teaching', 'Teaching'), ('service', 'Service / Administrative'), ('research', 'Research')], default='', help_text='Teaching → assign a Department. Service → assign a Service Unit. Research → assign a Research Unit.', max_length=20, verbose_name='Staff Track')),
                ('employment_type', models.CharField(blank=True, choices=[('permanent', 'Permanent'), ('contract', 'Contract'), ('part_time', 'Part-Time'), ('intern', 'Intern')], default='', max_length=20, verbose_name='Employment Type')),
                ('employed_on', models.DateField(blank=True, null=True, verbose_name='Employed On')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('qr_code_image', models.ImageField(blank=True, help_text="Auto-generated QR code linking to this employee's profile page.", null=True, upload_to=apps.staff.models.qr_upload_path, verbose_name='QR Code')),
                ('slug', autoslug.fields.AutoSlugField(always_update=True, editable=True, help_text='Human-readable part of the URL (name only). Not used for lookup.', max_length=300, populate_from=apps.staff.models.get_employee_slug, verbose_name='Slug')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Employee',
                'verbose_name_plural': 'Employees',
            },
        ),
    ]
