# Generated by Django 5.2.15 on 2026-06-12 20:16

import apps.staff.models
import autoslug.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('faculty_name', models.CharField(help_text="Official name of the faculty (e.g., 'Agriculture')", max_length=255, unique=True, verbose_name='Faculty Name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('slug', autoslug.fields.AutoSlugField(always_update=True, blank=True, editable=True, null=True, populate_from='faculty_name', unique=True, verbose_name='Slug')),
            ],
            options={
                'verbose_name': 'Faculty',
                'verbose_name_plural': 'Faculties',
                'ordering': ['faculty_name'],
            },
        ),
        migrations.CreateModel(
            name='ServiceUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of office, directorate, or administrative unit', max_length=255, unique=True, verbose_name='Service Unit Name')),
                ('slug', autoslug.fields.AutoSlugField(always_update=True, blank=True, editable=True, null=True, populate_from='name', unique=True, verbose_name='Slug')),
                ('description', models.TextField(blank=True, null=True)),
                ('unit_type', models.CharField(blank=True, choices=[('OFFICE', 'Office'), ('DIRECTORATE', 'Directorate'), ('BOARD', 'Board'), ('CENTRE', 'Centre'), ('OTHER', 'Other')], max_length=50, null=True, verbose_name='Unit Type')),
            ],
            options={
                'verbose_name': 'Service Unit',
                'verbose_name_plural': 'Service Units',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ResearchUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of institute or research centre', max_length=255, unique=True, verbose_name='Research Unit Name')),
                ('slug', autoslug.fields.AutoSlugField(always_update=True, blank=True, editable=True, null=True, populate_from='name', unique=True, verbose_name='Slug')),
                ('description', models.TextField(blank=True, null=True)),
                ('unit_type', models.CharField(blank=True, choices=[('INSTITUTE', 'Institute'), ('CENTRE', 'Centre')], max_length=20, null=True, verbose_name='Unit Type')),
                ('parent_faculty', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='research_units', to='staff.faculty', verbose_name='Parent Faculty')),
            ],
            options={
                'verbose_name': 'Research Unit',
                'verbose_name_plural': 'Research Units',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Department Name')),
                ('slug', autoslug.fields.AutoSlugField(always_update=True, editable=True, null=True, populate_from=apps.staff.models.get_department_slug, unique=True, verbose_name='Slug')),
                ('description', models.TextField(blank=True, null=True)),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departments', to='staff.faculty', verbose_name='Faculty')),
            ],
            options={
                'verbose_name': 'Department',
                'verbose_name_plural': 'Departments',
                'ordering': ['name'],
                'unique_together': {('name', 'faculty')},
            },
        ),
    ]
