# Generated by Django 5.2.15 on 2026-06-16 01:11

import apps.staff.models
import autoslug.fields
import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('faculty_name', models.CharField(help_text="Official name of the faculty (e.g., 'Agriculture')", max_length=255, unique=True, verbose_name='Faculty Name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('slug', autoslug.fields.AutoSlugField(always_update=True, blank=True, editable=True, null=True, populate_from='faculty_name', unique=True, verbose_name='Slug')),
            ],
            options={
                'verbose_name': 'Faculty',
                'verbose_name_plural': 'Faculties',
                'ordering': ['faculty_name'],
            },
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('level', models.PositiveSmallIntegerField(default=5, help_text='Seniority rank: 5 (most junior) – 15 (most senior)', validators=[django.core.validators.MinValueValidator(5), django.core.validators.MaxValueValidator(15)])),
            ],
            options={
                'verbose_name': 'Position',
                'verbose_name_plural': 'Positions',
                'ordering': ['-level', 'title'],
            },
        ),
        migrations.CreateModel(
            name='ServiceUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of office, directorate, or administrative unit', max_length=255, unique=True, verbose_name='Service Unit Name')),
                ('slug', autoslug.fields.AutoSlugField(always_update=True, blank=True, editable=True, null=True, populate_from='name', unique=True, verbose_name='Slug')),
                ('description', models.TextField(blank=True, null=True)),
                ('unit_type', models.CharField(blank=True, choices=[('OFFICE', 'Office'), ('DIRECTORATE', 'Directorate'), ('BOARD', 'Board'), ('CENTRE', 'Centre'), ('OTHER', 'Other')], max_length=50, null=True, verbose_name='Unit Type')),
            ],
            options={
                'verbose_name': 'Service Unit',
                'verbose_name_plural': 'Service Units',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Department Name')),
                ('slug', autoslug.fields.AutoSlugField(always_update=True, editable=True, null=True, populate_from=apps.staff.models.get_department_slug, unique=True, verbose_name='Slug')),
                ('description', models.TextField(blank=True, null=True)),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departments', to='staff.faculty', verbose_name='Faculty')),
            ],
            options={
                'verbose_name': 'Department',
                'verbose_name_plural': 'Departments',
                'ordering': ['name'],
                'unique_together': {('name', 'faculty')},
            },
        ),
        migrations.CreateModel(
            name='ResearchUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of institute or research centre', max_length=255, unique=True, verbose_name='Research Unit Name')),
                ('slug', autoslug.fields.AutoSlugField(always_update=True, blank=True, editable=True, null=True, populate_from='name', unique=True, verbose_name='Slug')),
                ('description', models.TextField(blank=True, null=True)),
                ('unit_type', models.CharField(blank=True, choices=[('INSTITUTE', 'Institute'), ('CENTRE', 'Centre')], max_length=20, null=True, verbose_name='Unit Type')),
                ('parent_faculty', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='research_units', to='staff.faculty', verbose_name='Parent Faculty')),
            ],
            options={
                'verbose_name': 'Research Unit',
                'verbose_name_plural': 'Research Units',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('staff_id', models.CharField(max_length=50, unique=True, verbose_name='Staff ID')),
                ('national_id', models.CharField(blank=True, max_length=50, unique=True, verbose_name='National ID')),
                ('honorific', models.CharField(blank=True, choices=[('mr', 'Mr'), ('mrs', 'Mrs'), ('ms', 'Ms'), ('miss', 'Miss'), ('dr', 'Dr'), ('prof', 'Prof')], default='', help_text='Courtesy title (e.g., Mr, Mrs, Dr, Prof). If empty, system may derive from academic rank.', max_length=10, verbose_name='Honorific')),
                ('academic_rank', models.CharField(blank=True, choices=[('graduate_assistant', 'Graduate Assistant'), ('tutorial_fellow', 'Tutorial Fellow'), ('lecturer', 'Lecturer'), ('senior_lecturer', 'Senior Lecturer'), ('associate_professor', 'Associate Professor'), ('professor', 'Professor'), ('research_fellow', 'Research Fellow'), ('senior_research_fellow', 'Senior Research Fellow'), ('research_professor', 'Research Professor')], default='', help_text='Formal academic rank: Lecturer, Senior Lecturer, Associate Professor, Professor, etc.', max_length=50, verbose_name='Academic Rank')),
                ('given_name', models.CharField(max_length=255, verbose_name='Given Name')),
                ('middle_name', models.CharField(blank=True, default='', max_length=255, verbose_name='Middle Name')),
                ('family_name', models.CharField(max_length=255, verbose_name='Family Name')),
                ('photo', models.ImageField(blank=True, help_text='Upload a custom profile photo. If empty, Google profile photo will be used as fallback.', null=True, upload_to='employee_photos/', verbose_name='Profile Photo')),
                ('google_photo_url', models.URLField(blank=True, default='', help_text='Populated from Google OAuth. Used as fallback when no custom photo is uploaded.', max_length=500, verbose_name='Google Profile Photo URL')),
                ('date_of_birth', models.DateField(verbose_name='Date of Birth')),
                ('alt_email_address', models.EmailField(blank=True, max_length=254, null=True, unique=True, verbose_name='Alternate Email Address')),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True, verbose_name='Phone Number')),
                ('alt_phone_number', models.CharField(blank=True, default='', max_length=20, verbose_name='Alternate Phone Number')),
                ('staff_track', models.CharField(blank=True, choices=[('teaching', 'Teaching'), ('service', 'Service / Administrative'), ('research', 'Research')], default='', help_text='Teaching → assign a Department. Service → assign a Service Unit. Research → assign a Research Unit.', max_length=20, verbose_name='Staff Track')),
                ('employment_type', models.CharField(blank=True, choices=[('permanent', 'Permanent'), ('contract', 'Contract'), ('part_time', 'Part-Time'), ('intern', 'Intern')], default='', max_length=20, verbose_name='Employment Type')),
                ('date_joined', models.DateField(blank=True, null=True, verbose_name='Date Joined')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('qr_code_image', models.ImageField(blank=True, help_text="Auto-generated QR code linking to this employee's profile page.", null=True, upload_to=apps.staff.models.qr_upload_path, verbose_name='QR Code')),
                ('slug', autoslug.fields.AutoSlugField(always_update=True, editable=True, help_text='Human-readable part of the URL (name only). Not used for lookup.', max_length=300, populate_from=apps.staff.models.get_employee_slug, verbose_name='Slug')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(blank=True, help_text='Required for teaching staff.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='staff.department', verbose_name='Department')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='employee', to=settings.AUTH_USER_MODEL, verbose_name='User Account')),
                ('position', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='staff.position', verbose_name='Position')),
                ('research_unit', models.ForeignKey(blank=True, help_text='Required for research staff.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='staff.researchunit', verbose_name='Research Unit')),
                ('service_unit', models.ForeignKey(blank=True, help_text='Required for service / administrative staff.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='staff.serviceunit', verbose_name='Service Unit')),
            ],
            options={
                'verbose_name': 'Employee',
                'verbose_name_plural': 'Employees',
                'indexes': [models.Index(fields=['family_name', 'given_name'], name='staff_name_idx'), models.Index(fields=['staff_track'], name='staff_track_idx'), models.Index(fields=['is_active'], name='active_staff_idx')],
            },
        ),
    ]
