# Generated by Django 5.2.15 on 2026-06-18 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True, verbose_name='Date of Birth'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='staff_id',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Staff ID'),
        ),
    ]
