# Generated by Django 5.2.15 on 2026-08-05 18:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('staff', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='employee', to=settings.AUTH_USER_MODEL, verbose_name='User Account'),
        ),
        migrations.AddField(
            model_name='department',
            name='faculty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departments', to='staff.faculty', verbose_name='Faculty'),
        ),
        migrations.AddField(
            model_name='employee',
            name='position',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='staff.position', verbose_name='Position'),
        ),
        migrations.AddField(
            model_name='researchunit',
            name='parent_faculty',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='research_units', to='staff.faculty', verbose_name='Parent Faculty'),
        ),
        migrations.AddField(
            model_name='employee',
            name='research_unit',
            field=models.ForeignKey(blank=True, help_text='Required for research staff.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='staff.researchunit', verbose_name='Research Unit'),
        ),
        migrations.AddField(
            model_name='employee',
            name='service_unit',
            field=models.ForeignKey(blank=True, help_text='Required for service / administrative staff.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='staff.serviceunit', verbose_name='Service Unit'),
        ),
        migrations.AlterUniqueTogether(
            name='department',
            unique_together={('name', 'faculty')},
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['staff_track'], name='staff_track_idx'),
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['is_active'], name='active_staff_idx'),
        ),
    ]
