# Generated by Django 5.2.15 on 2026-09-07 14:21

import apps.staff.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='qr_code_image',
            field=models.ImageField(blank=True, help_text="Auto-generated QR code linking to this employee's profile page.", max_length=255, null=True, upload_to=apps.staff.models.qr_upload_path, verbose_name='QR Code'),
        ),
    ]
