# Generated by Django 5.2.15 on 2026-07-10 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0003_alter_employee_national_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='google_photo_url',
            field=models.URLField(blank=True, default='', help_text='Populated from Google OAuth. Used as fallback when no custom photo is uploaded.', max_length=2000, verbose_name='Google Profile Photo URL'),
        ),
    ]
