# Generated by Django 5.2.15 on 2026-07-15 01:03

import apps.staff.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0004_alter_employee_google_photo_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='photo',
            field=models.ImageField(blank=True, help_text='Upload a custom profile photo. If empty, Google profile photo will be used as fallback.', null=True, upload_to=apps.staff.models.employee_photo_upload_path, verbose_name='Profile Photo'),
        ),
    ]
