server {
    listen 80;
    server_name uonalumni.or.ke www.uonalumni.or.ke staff.uonalumni.or.ke students.uonalumni.or.ke;
    return 301 https://www.uonalumni.or.ke$request_uri;
}

server {
    listen 443 ssl;
    server_name uonalumni.or.ke;
    ssl_certificate /etc/letsencrypt/live/www.uonalumni.or.ke/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/www.uonalumni.or.ke/privkey.pem;
    return 301 https://www.uonalumni.or.ke$request_uri;
}

server {
    listen 443 ssl;
    server_name www.uonalumni.or.ke;
    client_max_body_size 20M;
    ssl_certificate /etc/letsencrypt/live/www.uonalumni.or.ke/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/www.uonalumni.or.ke/privkey.pem;
    location = /favicon.ico { access_log off; log_not_found off; }
    location /static/ { alias /home/armando_salazar/webapps/uon_alumni_II/staticfiles/; }
    location /media/ { alias /home/armando_salazar/webapps/uon_alumni_II/media/; }
    location / { include proxy_params; proxy_pass http://127.0.0.1:8000; }
}

server {
    listen 443 ssl;
    server_name staff.uonalumni.or.ke;
    client_max_body_size 20M;
    ssl_certificate /etc/letsencrypt/live/www.uonalumni.or.ke/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/www.uonalumni.or.ke/privkey.pem;
    location = /favicon.ico { access_log off; log_not_found off; }
    location /static/ { alias /home/armando_salazar/webapps/uon_alumni_II/staticfiles/; }
    location /media/ { alias /home/armando_salazar/webapps/uon_alumni_II/media/; }
    location / { include proxy_params; proxy_pass http://127.0.0.1:8000; }
}

server {
    listen 443 ssl;
    server_name students.uonalumni.or.ke;
    client_max_body_size 20M;
    ssl_certificate /etc/letsencrypt/live/www.uonalumni.or.ke/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/www.uonalumni.or.ke/privkey.pem;
    location = /favicon.ico { access_log off; log_not_found off; }
    location /static/ { alias /home/armando_salazar/webapps/uon_alumni_II/staticfiles/; }
    location /media/ { alias /home/armando_salazar/webapps/uon_alumni_II/media/; }
    location / { include proxy_params; proxy_pass http://127.0.0.1:8000; }
}
