# Generated by Django 5.2.15 on 2026-06-15 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_user_options_remove_user_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email_verified',
            field=models.BooleanField(default=False, help_text="Whether Google has verified the user's email address.", verbose_name='Email Verified by Google'),
        ),
        migrations.AddField(
            model_name='user',
            name='google_sub',
            field=models.CharField(blank=True, help_text="Google's immutable user ID from the sub claim. Used to link Google accounts.", max_length=255, null=True, unique=True, verbose_name='Google Unique ID (sub)'),
        ),
        migrations.AddField(
            model_name='user',
            name='hd',
            field=models.CharField(blank=True, help_text="Only present for Google Workspace accounts – the user's organisation domain.", max_length=255, verbose_name='Hosted Domain (Google Workspace)'),
        ),
        migrations.AddField(
            model_name='user',
            name='locale',
            field=models.CharField(blank=True, help_text="User's preferred language (e.g., 'en', 'fr', 'de').", max_length=10, verbose_name='Locale'),
        ),
    ]
