# Generated by Django 5.2.15 on 2026-09-07 14:21

import apps.user.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_userprofile_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='photo',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to=apps.user.models.profile_photo_path),
        ),
    ]
