# Generated by Django 5.2.15 on 2026-07-10 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_user_email_verified_user_google_sub_user_hd_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='google_photo_url',
            field=models.URLField(blank=True, default='', max_length=2000, verbose_name='Google Profile Photo'),
        ),
    ]
