# Generated by Django 5.2.15 on 2026-06-05 01:28

import apps.home.models
import autoslug.fields
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import django_resized.forms
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(blank=True, help_text='Please add a short text about the banner ', max_length=75, null=True, verbose_name='Descriptive text')),
                ('top_banner', django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, help_text='Upload your item images ', keep_meta=True, null=True, quality=95, scale=None, size=[1400, 1400], upload_to='banner/top_banner/%Y/%m/%d/')),
                ('middle_banner', django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, help_text='Upload your item images ', keep_meta=True, null=True, quality=95, scale=None, size=[1400, 1400], upload_to='banner/middle_banner/%Y/%m/%d/')),
                ('bottom_banner', django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, help_text='Upload your item images ', keep_meta=True, null=True, quality=95, scale=None, size=[1400, 1400], upload_to='banner/bottom_banner/%Y/%m/%d/')),
                ('image', django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, help_text='Upload banner images ', keep_meta=True, null=True, quality=95, scale=None, size=[1400, 1400], upload_to='banner/image/%Y/%m/%d/')),
                ('logo', django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, help_text='Upload your item images ', keep_meta=True, null=True, quality=95, scale=None, size=[400, 400], upload_to='banner/logo/%Y/%m/%d/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Banner Image',
                'verbose_name_plural': 'Banner Images',
            },
        ),
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('about', models.TextField(blank=True, null=True)),
                ('year_launched', models.DateTimeField(blank=True, null=True, verbose_name='Launched On ')),
                ('slug', autoslug.fields.AutoSlugField(always_update=True, blank=True, editable=True, null=True, populate_from='name', unique_with=['year_launched'])),
                ('thumbnail', django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, help_text='Chapter banner ', keep_meta=True, null=True, quality=95, scale=None, size=[1080, 1080], upload_to='chapter/uploads/%Y/%m/%d/')),
            ],
            options={
                'verbose_name': 'Chapter',
                'verbose_name_plural': 'Chapters',
            },
        ),
        migrations.CreateModel(
            name='CoreValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField()),
                ('svg_path', models.TextField(blank=True, help_text='SVG path data for the icon')),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order')),
                ('is_active', models.BooleanField(default=True)),
                ('background_image', models.ImageField(blank=True, help_text='Background image for this core value', null=True, upload_to='core_values/bg/')),
                ('background_color', models.CharField(default='#ffffff', help_text='Fallback background color (hex code)', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Core Value',
                'verbose_name_plural': 'Core Values',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Executive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(choices=[('DR.', 'DR.'), ('ESQ.', 'ESQ.'), ('HON.', 'HON.'), ('ESQ.', 'ESQ.'), ('HON.', 'HON.'), ('MR.', 'MR.'), ('MRS.', 'MRS.'), ('Ms.', 'Ms.'), ('PROF.', 'PROF.'), ('REV.', 'REV.'), ('Rt. Hon.', 'Rt. Hon.'), ('SR.', 'SR.')], max_length=10)),
                ('position', models.CharField(blank=True, choices=[('CHAIRMAN', 'CHAIRMAN'), ('VICE CHAIR', 'VICE CHAIR'), ('SECRETARY', 'SECRETARY'), ('DEPUTY SECRETARY', 'DEPUTY SECRETARY'), ('ORGANISING SECRETARY', 'ORGANISING SECRETARY'), ('DEPUTY ORGANISING SECRETARY', 'DEPUTY ORGANISING SECRETARY'), ('TREASURER', 'TREASURER'), ('DEPUTY TREASURER', 'DEPUTY TREASURER'), ('EDITOR', 'EDITOR')], help_text=' Executive Committee Position', max_length=255, null=True, verbose_name='Executive Committee Position')),
                ('rank', models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10')], help_text=' Executive Rank', max_length=255, null=True, verbose_name='Executive Committee Rank')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='First Name')),
                ('middle_name', models.CharField(blank=True, max_length=150, verbose_name='Middle Name')),
                ('surname', models.CharField(blank=True, max_length=150, verbose_name='Surname')),
                ('bio', models.TextField(blank=True, max_length=2500, null=True, verbose_name='Bio')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='gallery/executive/')),
            ],
            options={
                'verbose_name': 'Executive',
                'verbose_name_plural': 'Executive',
            },
        ),
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', autoslug.fields.AutoSlugField(always_update=True, blank=True, editable=True, null=True, populate_from='name')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Faculty',
                'verbose_name_plural': 'Faculties',
            },
        ),
        migrations.CreateModel(
            name='MembershipTier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('fee', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tier_type', models.CharField(choices=[('life', 'Life Member'), ('annual', 'Annual Member'), ('honorary', 'Honorary Member'), ('corporate', 'Corporate Partner')], max_length=20)),
                ('duration_months', models.IntegerField(default=0, help_text='0 = lifetime')),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Secretariat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(choices=[('DR.', 'DR.'), ('ESQ.', 'ESQ.'), ('HON.', 'HON.'), ('ESQ.', 'ESQ.'), ('HON.', 'HON.'), ('MR.', 'MR.'), ('MRS.', 'MRS.'), ('Ms.', 'Ms.'), ('PROF.', 'PROF.'), ('REV.', 'REV.'), ('Rt. Hon.', 'Rt. Hon.'), ('SR.', 'SR.')], max_length=10)),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='First Name')),
                ('middle_name', models.CharField(blank=True, max_length=150, verbose_name='Middle Name')),
                ('surname', models.CharField(blank=True, max_length=150, verbose_name='Surname')),
                ('position', models.CharField(blank=True, choices=[('EXECUTIVE DIRECTOR', 'EXECUTIVE DIRECTOR'), ('ASSISTANT ADMINISTRATOR', 'ASSISTANT ADMINISTRATOR'), ('SENIOR ICT OFFICER', 'SENIOR ICT OFFICER'), ('SECRETARY', 'SECRETARY'), ('EDITOR', 'EDITOR')], help_text='Secretariat Position', max_length=255, null=True, verbose_name='Secretariat Position')),
                ('rank', models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10')], help_text='Secretariat Rank', max_length=255, null=True, verbose_name='Secretariat Rank')),
                ('bio', models.TextField(blank=True, max_length=2500, null=True, verbose_name='Bio')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='gallery/secretariat/')),
            ],
            options={
                'verbose_name': 'Secretariat',
                'verbose_name_plural': 'Secretariat',
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('article_type', models.CharField(choices=[('article', 'Article'), ('workshop', 'Workshop'), ('conference', 'Conference'), ('forum', 'Forum'), ('training', 'Training')], default='article', max_length=50, verbose_name='Article Type')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', apps.home.models.Title(help_text='Required', max_length=250, verbose_name='Title')),
                ('body', models.TextField()),
                ('quote', models.TextField(blank=True, max_length=1000, null=True)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='articles/images/')),
                ('article_banner_image', models.ImageField(blank=True, null=True, upload_to='articles/banners/')),
                ('thumbnail_url', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, default=django.utils.timezone.now, verbose_name='Created at')),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='date updated')),
                ('slug', autoslug.fields.AutoSlugField(always_update=True, editable=True, populate_from='title', unique_with=['created_at'])),
                ('is_feature', models.BooleanField(default=False)),
                ('is_highlighted', models.BooleanField(default=False)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articles', to=settings.AUTH_USER_MODEL)),
                ('chapter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='home.chapter')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('title', 'created_at')},
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', apps.home.models.Title(help_text='Required', max_length=250, verbose_name='Title')),
                ('body', models.TextField()),
                ('thumbnail', django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, null=True, quality=95, scale=None, size=[3648, 3648], upload_to='walk/images/')),
                ('created_at', models.DateTimeField(blank=True, default=django.utils.timezone.now, verbose_name='Created at')),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='date updated')),
                ('slug', autoslug.fields.AutoSlugField(always_update=True, editable=True, populate_from='title', unique_with=['created_at'])),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('title', 'created_at')},
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('faculty', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='departments', to='home.faculty')),
            ],
            options={
                'verbose_name': 'Department',
                'verbose_name_plural': 'Departments',
            },
        ),
        migrations.AddField(
            model_name='chapter',
            name='faculty',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chapters', to='home.faculty'),
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, help_text='Upload your image ', keep_meta=True, null=True, quality=95, scale=None, size=[1400, 1400], upload_to='gallery/image-uploads')),
                ('alt_text', models.CharField(blank=True, help_text='Please add a short alternative about the image', max_length=100, null=True, verbose_name='Alternative text')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('article', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='home.article')),
                ('chapter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='home.chapter')),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='home.event')),
            ],
            options={
                'verbose_name': 'Gallery Image',
                'verbose_name_plural': 'Gallery Images',
            },
        ),
        migrations.CreateModel(
            name='AlumniProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(choices=[('Mr', 'Mr'), ('Mrs', 'Mrs'), ('Ms', 'Ms'), ('Dr', 'Dr'), ('Prof', 'Prof'), ('Rev', 'Rev'), ('Other', 'Other')], max_length=10)),
                ('surname', models.CharField(max_length=100)),
                ('first_name', models.CharField(max_length=100)),
                ('middle_name', models.CharField(blank=True, max_length=100)),
                ('maiden_name', models.CharField(blank=True, max_length=100)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1)),
                ('date_of_birth', models.DateField()),
                ('id_passport_no', models.CharField(max_length=50, unique=True)),
                ('nationality', models.CharField(default='Kenyan', max_length=100)),
                ('postal_address', models.CharField(blank=True, max_length=200)),
                ('postal_code', models.CharField(blank=True, max_length=20)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('phone_mobile', models.CharField(max_length=15, validators=[django.core.validators.RegexValidator('^\\+?254\\d{9}$', message='Enter a valid Kenyan phone number (e.g., 2547XXXXXXXX)')])),
                ('phone_alt', models.CharField(blank=True, max_length=15)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('graduation_year', models.IntegerField(blank=True, null=True)),
                ('student_reg_no', models.CharField(blank=True, max_length=50)),
                ('membership_expiry', models.DateField(blank=True, null=True)),
                ('is_lifetime_member', models.BooleanField(default=False)),
                ('membership_number', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('membership_card_issued', models.BooleanField(default=False)),
                ('certificate_issued', models.BooleanField(default=False)),
                ('certificate_sent', models.BooleanField(default=False)),
                ('certificate_generated_at', models.DateTimeField(blank=True, null=True)),
                ('lapel_badge_issued', models.BooleanField(default=False)),
                ('receive_newsletter', models.BooleanField(default=True)),
                ('receive_sms_alerts', models.BooleanField(default=True)),
                ('registration_date', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='alumni_profile', to=settings.AUTH_USER_MODEL)),
                ('faculty', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.faculty')),
                ('current_membership_tier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.membershiptier')),
            ],
        ),
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', apps.home.models.Title(help_text='Required', max_length=250, verbose_name='Title')),
                ('relation', models.CharField(blank=True, help_text='Relation with UoNAA ', max_length=125, null=True, verbose_name='Partner Relation')),
                ('thumbnail', django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, null=True, quality=95, scale=None, size=[3648, 3648], upload_to='gallery/partners/')),
                ('created_at', models.DateTimeField(blank=True, default=django.utils.timezone.now, verbose_name='Created at')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('title', 'created_at')},
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('payment_method', models.CharField(choices=[('mpesa', 'M-Pesa'), ('credit_card', 'Credit/Debit Card'), ('bank_transfer', 'Bank Transfer'), ('cash', 'Cash'), ('cheque', 'Cheque')], max_length=20)),
                ('payment_status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed'), ('refunded', 'Refunded'), ('pending_verification', 'Pending Verification')], default='pending', max_length=20)),
                ('transaction_reference', models.CharField(default=uuid.uuid4, max_length=100, unique=True)),
                ('mpesa_receipt_number', models.CharField(blank=True, max_length=50, null=True)),
                ('bank_reference', models.CharField(blank=True, max_length=100, null=True)),
                ('mpesa_number', models.CharField(blank=True, max_length=15, null=True)),
                ('card_last_four', models.CharField(blank=True, max_length=4, null=True)),
                ('bank_name', models.CharField(blank=True, max_length=100, null=True)),
                ('payment_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('completion_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notes', models.TextField(blank=True)),
                ('alumni', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='home.alumniprofile')),
                ('membership_tier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='home.membershiptier')),
                ('processed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_payments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-payment_date'],
            },
        ),
        migrations.CreateModel(
            name='PaymentTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('initiate', 'Initiated'), ('callback', 'Callback Received'), ('verify', 'Verification'), ('complete', 'Completed'), ('fail', 'Failed'), ('refund', 'Refunded'), ('status_change', 'Status Changed')], max_length=20)),
                ('request_data', models.JSONField(blank=True, null=True)),
                ('response_data', models.JSONField(blank=True, null=True)),
                ('status_code', models.IntegerField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='home.payment')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['transaction_reference'], name='home_paymen_transac_688918_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['payment_status'], name='home_paymen_payment_657696_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['payment_date'], name='home_paymen_payment_f364d8_idx'),
        ),
        migrations.AddIndex(
            model_name='paymenttransaction',
            index=models.Index(fields=['payment', 'created_at'], name='home_paymen_payment_54b8e4_idx'),
        ),
    ]
