# Generated by Django 5.2.15 on 2026-08-05 21:32

import autoslug.fields
import cloudinary_storage.storage
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
        ('staff', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='article_type',
        ),
        migrations.RemoveField(
            model_name='article',
            name='thumbnail_url',
        ),
        migrations.AddField(
            model_name='article',
            name='is_published',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='article',
            name='page_key',
            field=models.CharField(blank=True, choices=[('history', 'History'), ('donate', 'Donate'), ('scholarship', 'Scholarship'), ('contact', 'Contact Us')], help_text="Set only for Type='Standing Page'. Fetch pages by this, never by slug.", max_length=20, null=True, unique=True, verbose_name='Page Key'),
        ),
        migrations.AddField(
            model_name='article',
            name='published_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='type',
            field=models.CharField(choices=[('page', 'Standing Page'), ('news', 'News'), ('feature', 'Feature'), ('notice', 'Notice')], default='news', help_text="'Standing Page' + a Page Key below makes this the admin-editable copy for a fixed site page (History, Donate, ...). Everything else is ordinary published content.", max_length=20, verbose_name='Type'),
        ),
        migrations.AddField(
            model_name='event',
            name='event_type',
            field=models.CharField(choices=[('walk', 'Alumni Walk'), ('workshop', 'Workshop'), ('conference', 'Conference'), ('forum', 'Forum'), ('training', 'Training')], default='walk', max_length=20),
        ),
        migrations.AlterField(
            model_name='article',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=True, populate_from='title', unique_with=['created_at']),
        ),
        migrations.AlterField(
            model_name='chapter',
            name='slug',
            field=autoslug.fields.AutoSlugField(blank=True, editable=True, null=True, populate_from='name', unique_with=['year_launched']),
        ),
        migrations.AlterField(
            model_name='event',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=True, populate_from='title', unique_with=['created_at']),
        ),
        migrations.CreateModel(
            name='InMemoriam',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('honorific', models.CharField(blank=True, choices=[('mr', 'Mr'), ('mrs', 'Mrs'), ('ms', 'Ms'), ('miss', 'Miss'), ('dr', 'Dr'), ('prof', 'Prof'), ('rev', 'Rev'), ('hon', 'Hon'), ('esq', 'Esq')], max_length=10)),
                ('given_name', models.CharField(max_length=150)),
                ('family_name', models.CharField(max_length=150)),
                ('birth_year', models.PositiveIntegerField(blank=True, null=True)),
                ('death_year', models.PositiveIntegerField(blank=True, null=True)),
                ('graduation_year', models.PositiveIntegerField(blank=True, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='in_memoriam/')),
                ('tribute', models.TextField(blank=True)),
                ('published', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('faculty', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='in_memoriam_entries', to='home.faculty')),
            ],
            options={
                'verbose_name': 'In Memoriam Entry',
                'verbose_name_plural': 'In Memoriam',
                'ordering': ['family_name', 'given_name'],
            },
        ),
        migrations.CreateModel(
            name='JobPosting',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('company', models.CharField(max_length=255)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField()),
                ('application_url', models.URLField(blank=True)),
                ('application_email', models.EmailField(blank=True, max_length=254)),
                ('is_approved', models.BooleanField(default=False)),
                ('expires_on', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('posted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='job_postings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Job Posting',
                'verbose_name_plural': 'Job Postings',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('newsletter', 'Newsletter'), ('minutes', 'Committee Minutes'), ('annual_report', 'Annual Report'), ('policy', 'Policy'), ('financial_statement', 'Financial Statement'), ('form', 'Form')], max_length=30)),
                ('visibility', models.CharField(choices=[('public', 'Public'), ('members', 'Members Only'), ('committee', 'Committee Only')], default='public', max_length=20)),
                ('document_date', models.DateField()),
                ('volume', models.CharField(blank=True, max_length=20)),
                ('issue_number', models.CharField(blank=True, max_length=20)),
                ('is_approved', models.BooleanField(default=False)),
                ('file', models.FileField(storage=cloudinary_storage.storage.RawMediaCloudinaryStorage, upload_to='publications/%Y/%m/')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='publications/covers/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='publications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Publication',
                'verbose_name_plural': 'Publications',
                'ordering': ['-document_date'],
            },
        ),
    ]
