# Generated by Django 5.2.15 on 2026-07-13 20:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
        ('staff', '0004_alter_employee_google_photo_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumniprofile',
            name='faculty',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='staff.faculty'),
        ),
        migrations.AlterField(
            model_name='chapter',
            name='faculty',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chapters', to='staff.faculty'),
        ),
        migrations.DeleteModel(
            name='Department',
        ),
        migrations.DeleteModel(
            name='Faculty',
        ),
    ]
