# Generated by Django 5.2.15 on 2026-07-13 21:09

import apps.home.models
import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_alumniprofile_faculty_alter_chapter_faculty_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumniprofile',
            name='slug',
            field=autoslug.fields.AutoSlugField(always_update=True, blank=True, editable=True, null=True, populate_from=apps.home.models.get_alumni_profile_slug),
        ),
    ]
