# Generated by Django 5.2.15 on 2026-08-05 21:40

import django.db.models.deletion
import django_resized.forms
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_remove_article_article_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='images',
            name='in_memoriam',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='home.inmemoriam'),
        ),
        migrations.AddField(
            model_name='images',
            name='publication',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='home.publication'),
        ),
        migrations.AlterField(
            model_name='article',
            name='article_banner_image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, null=True, quality=90, scale=None, size=[1920, 1080], upload_to='articles/banners/'),
        ),
        migrations.AlterField(
            model_name='article',
            name='thumbnail',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, null=True, quality=90, scale=None, size=[1200, 1200], upload_to='articles/images/'),
        ),
        migrations.AlterField(
            model_name='corevalue',
            name='background_image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, help_text='Background image for this core value', keep_meta=True, null=True, quality=90, scale=None, size=[1600, 1600], upload_to='core_values/bg/'),
        ),
        migrations.AlterField(
            model_name='executive',
            name='avatar',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, null=True, quality=90, scale=None, size=[800, 800], upload_to='gallery/executive/'),
        ),
        migrations.AlterField(
            model_name='inmemoriam',
            name='photo',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, null=True, quality=90, scale=None, size=[800, 800], upload_to='in_memoriam/'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='cover_image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, null=True, quality=90, scale=None, size=[1000, 1000], upload_to='publications/covers/'),
        ),
        migrations.AlterField(
            model_name='secretariat',
            name='avatar',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, null=True, quality=90, scale=None, size=[800, 800], upload_to='gallery/secretariat/'),
        ),
    ]
