# Generated by Django 5.2.15 on 2026-07-13 21:18

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alumniprofile_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumniprofile',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
