# Generated by Django 5.2.15 on 2026-07-13 21:18
# Hand-edited: the original plain AlterField's auto-generated SQL
# (`ALTER COLUMN "id" TYPE uuid USING "id"::uuid`) works on SQLite (which
# just recreates the table) but fails on PostgreSQL -- there is no cast
# from bigint to uuid, since an integer like 42 isn't a valid UUID string.
# Both home_alumniprofile and home_payment (the only FK into it) are
# confirmed empty in every environment this has been checked against, so
# there's no data to preserve -- new rows just get a fresh random UUID.

import uuid

from django.db import migrations, models


def alter_id_to_uuid(apps, schema_editor):
    connection = schema_editor.connection

    if connection.vendor == "postgresql":
        with connection.cursor() as cursor:
            # Find and drop whatever the FK constraint happens to be named
            # in this environment (Django's auto-generated name includes a
            # hash, so don't hardcode it) -- required because Postgres
            # won't let either side's column type diverge from the other
            # while the constraint exists, deferred or not.
            cursor.execute(
                """
                DO $$
                DECLARE
                    fk_name text;
                BEGIN
                    SELECT tc.constraint_name INTO fk_name
                    FROM information_schema.table_constraints tc
                    JOIN information_schema.key_column_usage kcu
                        ON tc.constraint_name = kcu.constraint_name
                    WHERE tc.table_name = 'home_payment'
                      AND tc.constraint_type = 'FOREIGN KEY'
                      AND kcu.column_name = 'alumni_id';
                    IF fk_name IS NOT NULL THEN
                        EXECUTE format('ALTER TABLE home_payment DROP CONSTRAINT %I', fk_name);
                    END IF;
                END $$;
                """
            )
            # Modern Django (BigAutoField since 4.1) creates this as an
            # identity column, not the old serial+sequence-default style --
            # DROP DEFAULT doesn't apply to it and errors. DROP IDENTITY
            # IF EXISTS handles that case and is a safe no-op otherwise.
            cursor.execute("ALTER TABLE home_alumniprofile ALTER COLUMN id DROP IDENTITY IF EXISTS;")
            cursor.execute("ALTER TABLE home_alumniprofile ALTER COLUMN id DROP DEFAULT;")
            cursor.execute(
                "ALTER TABLE home_alumniprofile ALTER COLUMN id TYPE uuid USING gen_random_uuid();"
            )
            cursor.execute(
                "ALTER TABLE home_payment ALTER COLUMN alumni_id TYPE uuid USING NULL;"
            )
            cursor.execute(
                """
                ALTER TABLE home_payment
                    ADD CONSTRAINT home_payment_alumni_id_fk_home_alumniprofile
                    FOREIGN KEY (alumni_id) REFERENCES home_alumniprofile (id)
                    DEFERRABLE INITIALLY DEFERRED;
                """
            )
    else:
        # SQLite etc. -- the plain field-alter already works correctly
        # via Django's table-recreation strategy for these backends.
        AlumniProfile = apps.get_model("home", "AlumniProfile")
        old_field = AlumniProfile._meta.get_field("id")
        new_field = models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)
        new_field.set_attributes_from_name("id")
        new_field.model = AlumniProfile
        schema_editor.alter_field(AlumniProfile, old_field, new_field)


def alter_id_to_uuid_reverse(apps, schema_editor):
    raise NotImplementedError("Reversing this migration is not supported.")


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0003_alumniprofile_slug"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AlterField(
                    model_name="alumniprofile",
                    name="id",
                    field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
                ),
            ],
            database_operations=[
                migrations.RunPython(alter_id_to_uuid, alter_id_to_uuid_reverse),
            ],
        ),
    ]
