# Generated by Django 5.2.15 on 2026-08-05 21:51

import django_resized.forms
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_images_in_memoriam_images_publication_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='article_banner_image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, null=True, quality=85, scale=None, size=[2200, 2200], upload_to='articles/banners/'),
        ),
        migrations.AlterField(
            model_name='article',
            name='thumbnail',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, null=True, quality=85, scale=None, size=[1600, 1600], upload_to='articles/images/'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='bottom_banner',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, help_text='Upload your item images ', keep_meta=True, null=True, quality=85, scale=None, size=[2200, 2200], upload_to='banner/bottom_banner/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, help_text='Upload banner images ', keep_meta=True, null=True, quality=85, scale=None, size=[2200, 2200], upload_to='banner/image/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='logo',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, help_text='Upload your item images ', keep_meta=True, null=True, quality=90, scale=None, size=[500, 500], upload_to='banner/logo/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='middle_banner',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, help_text='Upload your item images ', keep_meta=True, null=True, quality=85, scale=None, size=[2200, 2200], upload_to='banner/middle_banner/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='top_banner',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, help_text='Upload your item images ', keep_meta=True, null=True, quality=85, scale=None, size=[2200, 2200], upload_to='banner/top_banner/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='chapter',
            name='thumbnail',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, help_text='Chapter banner ', keep_meta=True, null=True, quality=85, scale=None, size=[1600, 1600], upload_to='chapter/uploads/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='corevalue',
            name='background_image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, help_text='Background image for this core value', keep_meta=True, null=True, quality=85, scale=None, size=[2200, 2200], upload_to='core_values/bg/'),
        ),
        migrations.AlterField(
            model_name='event',
            name='thumbnail',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, null=True, quality=85, scale=None, size=[2200, 2200], upload_to='walk/images/'),
        ),
        migrations.AlterField(
            model_name='executive',
            name='avatar',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, null=True, quality=85, scale=None, size=[1200, 1200], upload_to='gallery/executive/'),
        ),
        migrations.AlterField(
            model_name='images',
            name='image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, help_text='Upload your image ', keep_meta=True, null=True, quality=85, scale=None, size=[2200, 2200], upload_to='gallery/image-uploads'),
        ),
        migrations.AlterField(
            model_name='inmemoriam',
            name='photo',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, null=True, quality=85, scale=None, size=[1200, 1200], upload_to='in_memoriam/'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='thumbnail',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, null=True, quality=85, scale=None, size=[1600, 1600], upload_to='gallery/partners/'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='cover_image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, null=True, quality=85, scale=None, size=[1600, 1600], upload_to='publications/covers/'),
        ),
        migrations.AlterField(
            model_name='secretariat',
            name='avatar',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, null=True, quality=85, scale=None, size=[1200, 1200], upload_to='gallery/secretariat/'),
        ),
    ]
