# Generated by Django 5.2.15 on 2026-07-13 22:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_alumniprofile_id'),
        ('staff', '0004_alter_employee_google_photo_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumniprofile',
            name='current_employer',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='alumniprofile',
            name='employment_position',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='alumniprofile',
            name='graduation_institution',
            field=models.CharField(blank=True, choices=[('uon', 'University of Nairobi (Alumni)'), ('other', 'Other Institution')], default='', max_length=10),
        ),
        migrations.AddField(
            model_name='alumniprofile',
            name='name_at_graduation',
            field=models.CharField(blank=True, default='', help_text='Only if different from your current name', max_length=300),
        ),
        migrations.AddField(
            model_name='alumniprofile',
            name='other_institution_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='alumniprofile',
            name='other_institution_qualification',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.CreateModel(
            name='Qualification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('phd', 'Doctor of Philosophy (PhD)'), ('masters', "Master's Degree"), ('bachelors', "Bachelor's Degree"), ('pgd', 'Postgraduate Diploma'), ('diploma', 'Diploma'), ('fellowship', 'Fellowship')], max_length=20)),
                ('name', models.CharField(max_length=255)),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qualifications', to='staff.faculty')),
            ],
            options={
                'verbose_name': 'Qualification',
                'verbose_name_plural': 'Qualifications',
                'ordering': ['faculty__faculty_name', 'level', 'name'],
                'unique_together': {('faculty', 'name')},
            },
        ),
        migrations.AddField(
            model_name='alumniprofile',
            name='qualification',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alumni', to='home.qualification'),
        ),
    ]
