# Generated by Django 5.2.15 on 2026-08-06 19:42

import django.db.models.deletion
import phonenumber_field.modelfields
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_article_page_key'),
        ('staff', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AlumniEmploymentRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order', models.PositiveSmallIntegerField(default=1)),
                ('organization', models.CharField(blank=True, default='', max_length=255)),
                ('position', models.CharField(blank=True, default='', max_length=255)),
                ('alumni_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employment_history', to='home.alumniprofile')),
            ],
            options={
                'verbose_name': 'Additional Employment Record',
                'verbose_name_plural': 'Additional Employment Records',
                'ordering': ['alumni_profile', 'order'],
            },
        ),
        migrations.CreateModel(
            name='AlumniPhoneNumber',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region='KE')),
                ('label', models.CharField(blank=True, default='', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='additional_phones', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Additional Phone Number',
                'verbose_name_plural': 'Additional Phone Numbers',
                'ordering': ['user', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='AlumniQualification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order', models.PositiveSmallIntegerField(default=1)),
                ('legacy_college', models.CharField(blank=True, default='', max_length=100)),
                ('course_name_raw', models.CharField(blank=True, default='', max_length=255)),
                ('graduation_year', models.IntegerField(blank=True, null=True)),
                ('alumni_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='additional_qualifications', to='home.alumniprofile')),
                ('faculty', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.faculty')),
                ('qualification', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='home.qualification')),
            ],
            options={
                'verbose_name': 'Additional Qualification',
                'verbose_name_plural': 'Additional Qualifications',
                'ordering': ['alumni_profile', 'order'],
            },
        ),
    ]
