# Generated by Django 5.2.15 on 2026-08-06 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_alumniemploymentrecord_alumniphonenumber_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='legacy_signed',
            field=models.BooleanField(default=False, help_text='Physical signature on file from a paper membership form (legacy import only).'),
        ),
        migrations.AddField(
            model_name='membership',
            name='subscription_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text="Amount actually paid/subscribed for this membership row. May differ from the tier's current fee.", max_digits=10, null=True),
        ),
    ]
