# Generated by Django 5.2.15 on 2026-08-06 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_membership_legacy_signed_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='page_key',
            field=models.CharField(blank=True, choices=[('history', 'History'), ('donate', 'Donate'), ('scholarship', 'Scholarship'), ('contact', 'Contact Us'), ('categories-benefits', 'Categories & Benefits'), ('alumni-card', 'Alumni Card'), ('corporates', 'Corporates'), ('notable-alumni', 'Our Notable Alumni'), ('agm', 'Annual General Meeting'), ('consultancy-training', 'Consultancy & Training'), ('terms', 'Terms of Service'), ('privacy', 'Privacy Policy'), ('cookies', 'Cookie Policy'), ('shop', 'Shop')], help_text="Set only for Type='Standing Page'. Fetch pages by this, never by slug.", max_length=20, null=True, unique=True, verbose_name='Page Key'),
        ),
    ]
