# Generated by Django 5.2.15 on 2026-08-07 17:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_alter_article_page_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='amount_paid',
            field=models.DecimalField(decimal_places=2, default=0, help_text="Cumulative amount paid toward this row's tier fee. For installment plans this is < tier.fee until paid off.", max_digits=10),
        ),
        migrations.AddField(
            model_name='membership',
            name='next_installment_due',
            field=models.DateField(blank=True, help_text='When the next installment is expected, based on payment_frequency. Only meaningful for installment plans (payment_frequency != Once).', null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='membership',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='installment_payments', to='home.membership'),
        ),
    ]
