# Generated by Django 5.2.15 on 2026-08-07 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_membership_amount_paid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('mpesa', 'M-Pesa'), ('credit_card', 'Credit/Debit Card'), ('bank_transfer', 'Bank Transfer')], max_length=20),
        ),
    ]
