# Generated by Django 5.2.15 on 2026-08-07 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_alter_payment_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumniprofile',
            name='qualification_name_raw',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
