# Generated by Django 5.2.15 on 2026-08-10 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_alumniprofile_qualification_name_raw'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('expired', 'Expired'), ('cancelled', 'Cancelled'), ('superseded', 'Superseded')], default='pending', max_length=20),
        ),
    ]
