# Generated by Django 5.2.15 on 2026-08-10 19:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_alter_membership_membership_number_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Benefit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('axis', models.CharField(choices=[('access', 'Access'), ('voice', 'Voice'), ('economic', 'Economic'), ('legacy', 'Legacy')], max_length=20)),
                ('description', models.TextField(blank=True, default='')),
                ('display_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Benefit',
                'verbose_name_plural': 'Benefits',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.AlterField(
            model_name='membershiptier',
            name='tier_type',
            field=models.CharField(choices=[('life', 'Life Member'), ('annual', 'Annual Member'), ('honorary', 'Honorary Member'), ('corporate', 'Corporate Partner'), ('student', 'Student Member'), ('registered', 'Registered Member')], max_length=20),
        ),
        migrations.CreateModel(
            name='TierBenefit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('included', 'Included'), ('excluded', 'Excluded'), ('not_applicable', 'Not applicable')], default='excluded', max_length=20)),
                ('detail', models.CharField(blank=True, default='', help_text='Qualifier for an included benefit, e.g. "2 vehicles", "25% off", "eligible". Leave blank for a plain ✓.', max_length=255)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('benefit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tier_benefits', to='home.benefit')),
                ('tier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tier_benefits', to='home.membershiptier')),
            ],
            options={
                'verbose_name': 'Tier Benefit',
                'verbose_name_plural': 'Tier Benefits',
                'ordering': ['display_order'],
                'unique_together': {('tier', 'benefit')},
            },
        ),
    ]
