# Generated by Django 5.2.15 on 2026-08-11 10:05

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_redesign_tier_benefits'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScholarshipApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submitted_at', models.DateTimeField(auto_now_add=True, verbose_name='Timestamp')),
                ('first_name', models.CharField(max_length=100, verbose_name='First/Baptismal')),
                ('middle_name', models.CharField(blank=True, max_length=100)),
                ('surname', models.CharField(max_length=100, verbose_name='Surname/Family Name')),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=10)),
                ('date_of_birth', models.DateField()),
                ('registration_number', models.CharField(max_length=30, unique=True, verbose_name='University registration number')),
                ('current_course', models.CharField(max_length=150)),
                ('year_of_study', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(6)])),
                ('department', models.CharField(max_length=150)),
                ('faculty', models.CharField(max_length=150)),
                ('mobile_no', models.CharField(max_length=20, verbose_name='Tel./Mobile No')),
                ('alternative_mobile_no', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('county_of_residence', models.CharField(max_length=100)),
                ('sub_county', models.CharField(max_length=100)),
                ('ward', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('sub_location', models.CharField(max_length=100)),
                ('school_name', models.CharField(max_length=200)),
                ('kcse_grade', models.CharField(max_length=5)),
                ('kcse_year', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1985), django.core.validators.MaxValueValidator(2026)])),
                ('school_phone_no', models.CharField(blank=True, max_length=20)),
                ('head_teacher_no', models.CharField(blank=True, max_length=20)),
                ('school_county', models.CharField(max_length=100)),
                ('other_achievement_1', models.TextField(blank=True, verbose_name='State any other Academic achievement')),
                ('other_achievement_2', models.TextField(blank=True)),
                ('physical_copy', models.FileField(upload_to='scholarship_applications/%Y/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'jpg', 'jpeg', 'png'])])),
                ('academic_level', models.CharField(choices=[('undergraduate', 'Undergraduate'), ('postgraduate', 'Postgraduate')], default='undergraduate', max_length=20)),
            ],
            options={
                'verbose_name': 'Scholarship Application',
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='InterviewScoreSheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('venue', models.CharField(default='Alumni Offices', max_length=150)),
                ('interview_date', models.DateField()),
                ('time_start', models.TimeField()),
                ('time_stop', models.TimeField()),
                ('course_undertaking', models.CharField(max_length=150)),
                ('score_about_yourself', models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(5)])),
                ('score_socioeconomic', models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(10)])),
                ('score_previous_education', models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(5)])),
                ('score_strength_weakness', models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(5)])),
                ('score_deserve_scholarship', models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(10)])),
                ('score_role_model', models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(5)])),
                ('score_family_status', models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(5)])),
                ('score_personality', models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(5)])),
                ('parental_status', models.CharField(choices=[('orphan', 'Orphan'), ('one_parent', 'One Parent'), ('both_parents', 'Both Parents')], max_length=15)),
                ('received_other_funding', models.BooleanField(verbose_name='Have you received other funding...')),
                ('verdict', models.IntegerField(choices=[(1, 'Qualifies for scholarship award'), (2, 'Does not qualify for scholarship award')])),
                ('prepared_by_name', models.CharField(max_length=150)),
                ('prepared_by_signature', models.CharField(blank=True, max_length=150)),
                ('other_remarks', models.TextField(blank=True)),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='score_sheet', to='home.scholarshipapplication')),
            ],
            options={
                'verbose_name': 'Interview Score Sheet',
            },
        ),
    ]
