# Generated by Django 5.2.15 on 2026-08-11 10:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_scholarshipapplication_interviewscoresheet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scholarshipapplication',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='scholarship_applications', to='home.department'),
        ),
        migrations.AlterField(
            model_name='scholarshipapplication',
            name='faculty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='scholarship_applications', to='home.faculty'),
        ),
    ]
