# Generated by Django 5.2.15 on 2026-08-11 11:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_alter_scholarshipapplication_department_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scholarshipapplication',
            name='year_of_study',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(7)]),
        ),
    ]
