# Generated by Django 5.2.15 on 2026-08-11 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0021_retire_physical_id_card'),
    ]

    operations = [
        migrations.AddField(
            model_name='images',
            name='show_in_carousel',
            field=models.BooleanField(default=False, help_text='Feature this image in the advert/promo carousel below the homepage banner.', verbose_name='Show in homepage carousel'),
        ),
    ]
