# Generated by Django 5.2.15 on 2026-08-12 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0022_images_show_in_carousel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scholarshipapplication',
            name='kcse_grade',
            field=models.CharField(choices=[('A', 'A'), ('A-', 'A-'), ('B+', 'B+'), ('B', 'B'), ('B-', 'B-'), ('C+', 'C+'), ('C', 'C'), ('C-', 'C-'), ('D+', 'D+'), ('D', 'D'), ('D-', 'D-'), ('E', 'E')], max_length=5, verbose_name='KCSE Grade'),
        ),
    ]
