# Generated by Django 5.2.15 on 2026-08-13 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0023_alter_scholarshipapplication_kcse_grade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scholarshipapplication',
            name='other_achievement_1',
            field=models.TextField(blank=True, verbose_name='State any other academic achievement'),
        ),
    ]
