# Hand-authored, not autogenerated -- see apps/student/migrations/0002 for
# the matching other half of this move.
#
# ScholarshipApplication/InterviewScoreSheet are moving to apps.student
# (2026-08-13): apps.home is the alumni-facing content site (people who
# have already graduated), and an undergraduate scholarship applicant is
# a prospective/current student, not an alumnus.
#
# state_operations only, empty database_operations: this tells Django's
# migration STATE that these models (and ScholarshipApplication's
# cross-app department/faculty fields specifically) no longer belong to
# `home`, WITHOUT dropping the actual home_scholarshipapplication /
# home_interviewscoresheet tables -- those get renamed in place by
# apps/student/migrations/0002, not recreated. Same
# SeparateDatabaseAndState technique (state vs. database) this project
# already relied on for the 2026-08-10 Faculty/Department Neon incident,
# there via a manual ALTER TABLE RENAME rather than Django operations,
# same underlying principle: change what Django (or SQL) calls something
# without touching the rows themselves.
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0025_alter_scholarshipapplication_county_of_residence'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.RemoveField(
                    model_name='scholarshipapplication',
                    name='department',
                ),
                migrations.RemoveField(
                    model_name='scholarshipapplication',
                    name='faculty',
                ),
                migrations.DeleteModel(
                    name='InterviewScoreSheet',
                ),
                migrations.DeleteModel(
                    name='ScholarshipApplication',
                ),
            ],
            database_operations=[],
        ),
    ]
