# Generated by Django 5.2.15 on 2026-08-13 23:49

import django_resized.forms
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0026_move_scholarship_models_to_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='page_background',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, help_text='Background image shown behind the scholarship, profile, and analytics pages.', keep_meta=True, null=True, quality=85, scale=None, size=[2200, 2200], upload_to='banner/page_background/%Y/%m/%d/'),
        ),
    ]
