# Generated by Django 5.2.15 on 2026-08-14 00:03

import django_resized.forms
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0027_banner_page_background'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='footer_logo',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, help_text="Footer logo -- usually a white/reversed variant of the main logo, for contrast against the footer's dark background.", keep_meta=True, null=True, quality=90, scale=None, size=[500, 500], upload_to='banner/footer_logo/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='bottom_banner',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, help_text='Footer background image (templates/snippets/footer.html).', keep_meta=True, null=True, quality=85, scale=None, size=[2200, 2200], upload_to='banner/bottom_banner/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='logo',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, help_text='Site logo -- navbar, top-left (templates/snippets/navbar.html).', keep_meta=True, null=True, quality=90, scale=None, size=[500, 500], upload_to='banner/logo/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='top_banner',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, help_text='Homepage hero background (templates/snippets/banner.html).', keep_meta=True, null=True, quality=85, scale=None, size=[2200, 2200], upload_to='banner/top_banner/%Y/%m/%d/'),
        ),
    ]
