# Generated by Django 5.2.15 on 2026-08-14 00:46

import apps.home.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0028_banner_footer_logo_alter_banner_bottom_banner_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumniprofile',
            name='qr_code_image',
            field=models.ImageField(blank=True, help_text="Auto-generated QR code linking to this alumnus's profile page.", null=True, upload_to=apps.home.models.alumni_qr_upload_path, verbose_name='QR Code'),
        ),
    ]
