# Generated by Django 5.2.15 on 2026-08-14 01:19

import django_resized.forms
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0029_alumniprofile_qr_code_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='alumni_qr_watermark',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, help_text='Crest embedded in the center of ALUMNI QR codes. Falls back to the UoNAA crest if unset.', keep_meta=True, null=True, quality=90, scale=None, size=[800, 800], upload_to='banner/alumni_qr_watermark/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='banner',
            name='staff_qr_watermark',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, help_text='Crest embedded in the center of STAFF QR codes. Falls back to the UoN crest if unset.', keep_meta=True, null=True, quality=90, scale=None, size=[800, 800], upload_to='banner/staff_qr_watermark/%Y/%m/%d/'),
        ),
    ]
