# Generated by Django 5.2.15 on 2026-08-17 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0030_banner_alumni_qr_watermark_banner_staff_qr_watermark'),
    ]

    operations = [
        migrations.AddField(
            model_name='membershiptier',
            name='can_stand_for_executive_committee',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='membershiptier',
            name='can_vote_governing_body',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='membershiptier',
            name='code',
            field=models.SlugField(blank=True, help_text='Stable key for this category, independent of the display name above -- get_or_create in the reconciliation command keys off this, never off name.', null=True, unique=True),
        ),
        migrations.AddField(
            model_name='membershiptier',
            name='constitution_reference',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='membershiptier',
            name='display_order',
            field=models.PositiveSmallIntegerField(blank=True, help_text="Position (1-11) in the Constitution's own category list. Separate from the existing 'order' field above, which predates this reconciliation.", null=True),
        ),
        migrations.AddField(
            model_name='membershiptier',
            name='eligibility_notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='membershiptier',
            name='eligible_for_appointment',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='membershiptier',
            name='fee_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text="Constitutional/provisional fee -- separate from the existing 'fee' field above, which is the actual current list price.", max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='membershiptier',
            name='fee_basis',
            field=models.CharField(blank=True, choices=[('one_off', 'One-off'), ('annual', 'Annual'), ('per_term', 'Per Term'), ('none', 'None')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='membershiptier',
            name='fee_is_provisional',
            field=models.BooleanField(default=False, help_text="True for every row the reconciliation command writes a fee_amount for -- the Constitution says 'prescribed fee' throughout and prescribes no amount."),
        ),
        migrations.AddField(
            model_name='membershiptier',
            name='holder_type',
            field=models.CharField(blank=True, choices=[('individual', 'Individual'), ('organisation', 'Organisation')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='membershiptier',
            name='is_life',
            field=models.BooleanField(blank=True, help_text='True means no expiry.', null=True),
        ),
        migrations.AddField(
            model_name='membershiptier',
            name='max_term_years',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='membershiptier',
            name='membership_cap',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='membershiptier',
            name='minimum_age',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='membershiptier',
            name='provisions_confirmed',
            field=models.BooleanField(default=False, help_text='False where the supplied constitutional text defines no provisions for this category.'),
        ),
        migrations.AddField(
            model_name='membershiptier',
            name='requires_executive_ratification',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='membershiptier',
            name='requires_general_assembly_election',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
