# Generated by Django 5.2.15 on 2026-08-18 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0031_membershiptier_can_stand_for_executive_committee_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_type', models.CharField(choices=[('alumni_registration_confirmation', 'Alumni Registration Confirmation'), ('evaluation_receipt', 'Evaluation Receipt')], max_length=50)),
                ('related_object_id', models.CharField(max_length=64)),
                ('recipient_email', models.EmailField(blank=True, max_length=254)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('email_type', 'related_object_id'), name='unique_email_log_per_object')],
            },
        ),
    ]
