# Generated by Django 5.2.15 on 2026-08-18 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0032_emaillog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emaillog',
            name='email_type',
            field=models.CharField(choices=[('alumni_registration_confirmation', 'Alumni Registration Confirmation'), ('evaluation_receipt', 'Evaluation Receipt'), ('newsletter_announcement', 'Newsletter Announcement')], max_length=50),
        ),
    ]
