# Generated by Django 5.2.15 on 2026-08-18 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0033_alter_emaillog_email_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emaillog',
            name='related_object_id',
            field=models.CharField(max_length=128),
        ),
    ]
