# Generated by Django 5.2.15 on 2026-08-20 00:52

import django_resized.forms
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0035_alter_article_page_key'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgramArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('description', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order')),
                ('is_active', models.BooleanField(default=True)),
                ('background_image', django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, help_text="Photo shown on this program's homepage card.", keep_meta=True, null=True, quality=85, scale=None, size=[2200, 2200], upload_to='program_areas/bg/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Program Area',
                'verbose_name_plural': 'Program Areas',
                'ordering': ['order', 'name'],
            },
        ),
    ]
