# Generated by Django 5.2.15 on 2026-08-20 19:57

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0036_programarea'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileClaimVerification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('channel', models.CharField(choices=[('email', 'Email'), ('phone', 'Phone')], default='email', max_length=10)),
                ('code_hash', models.CharField(blank=True, default='', max_length=128)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified'), ('consumed', 'Consumed')], default='pending', max_length=10)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='claim_verifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Profile Claim Verification',
                'verbose_name_plural': 'Profile Claim Verifications',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'status', 'expires_at'], name='home_profil_user_id_b436e9_idx'), models.Index(fields=['ip_address', 'created_at'], name='home_profil_ip_addr_e114d8_idx')],
            },
        ),
    ]
