# Generated by Django 5.2.15 on 2026-08-20 20:55

import django_resized.forms
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0037_profileclaimverification'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='profile_update_card_image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, help_text="Homepage 'Keep Your UoN Alumni Profile Up to Date' card image.", keep_meta=True, null=True, quality=85, scale=None, size=[2200, 2200], upload_to='banner/profile_update_card_image/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='banner',
            name='volunteer_card_image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, help_text="Homepage 'Volunteer and Share Your Experience' card image.", keep_meta=True, null=True, quality=85, scale=None, size=[2200, 2200], upload_to='banner/volunteer_card_image/%Y/%m/%d/'),
        ),
    ]
