# Generated by Django 5.2.15 on 2026-08-20 22:04

import django_resized.forms
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0038_banner_profile_update_card_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='programarea',
            name='background_image',
        ),
        migrations.AddField(
            model_name='banner',
            name='affinity_programs_image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, help_text="Homepage 'Affinity programs' card image.", keep_meta=True, null=True, quality=85, scale=None, size=[2200, 2200], upload_to='banner/program_areas/affinity_programs/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='banner',
            name='career_professional_programs_image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, help_text="Homepage 'Career and professional programs' card image.", keep_meta=True, null=True, quality=85, scale=None, size=[2200, 2200], upload_to='banner/program_areas/career_professional_programs/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='banner',
            name='off_campus_programs_image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, help_text="Homepage 'Off-campus programs' card image.", keep_meta=True, null=True, quality=85, scale=None, size=[2200, 2200], upload_to='banner/program_areas/off_campus_programs/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='banner',
            name='on_campus_programs_image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, help_text="Homepage 'On-campus programs' card image.", keep_meta=True, null=True, quality=85, scale=None, size=[2200, 2200], upload_to='banner/program_areas/on_campus_programs/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='banner',
            name='online_part_time_alumni_image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, help_text="Homepage 'Engagement of alumni of online and part-time degree programs' card image.", keep_meta=True, null=True, quality=85, scale=None, size=[2200, 2200], upload_to='banner/program_areas/online_part_time_alumni/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='banner',
            name='undergraduate_alumni_programs_image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, help_text="Homepage 'Programs for undergraduate students and undergraduate young alumni' card image.", keep_meta=True, null=True, quality=85, scale=None, size=[2200, 2200], upload_to='banner/program_areas/undergraduate_alumni_programs/%Y/%m/%d/'),
        ),
    ]
