# Generated by Django 5.2.15 on 2026-08-21 01:27

import django_resized.forms
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0039_remove_programarea_background_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumniprofile',
            name='digital_id_active',
            field=models.BooleanField(default=False, help_text='Must be checked by a Secretariat member for the uploaded Alumni Digital ID photo to actually display.', verbose_name='Alumni Digital ID Photo Approved'),
        ),
        migrations.AddField(
            model_name='alumniprofile',
            name='digital_id_photo',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, help_text='Formal photo for the Alumni Digital ID (badge + PDF). Falls back to the general profile photo if not set or not yet approved.', keep_meta=True, null=True, quality=90, scale=None, size=[800, 800], upload_to='alumni/digital_id_photos/%Y/%m/%d/', verbose_name='Alumni Digital ID Photo'),
        ),
        migrations.AlterField(
            model_name='article',
            name='page_key',
            field=models.CharField(blank=True, choices=[('history', 'History'), ('donate', 'Donate'), ('scholarship', 'Scholarship'), ('contact', 'Contact Us'), ('categories-benefits', 'Categories & Benefits'), ('digital-id', 'Alumni Digital ID'), ('corporates', 'Corporates'), ('notable-alumni', 'Our Notable Alumni'), ('agm', 'Annual General Meeting'), ('consultancy-training', 'Consultancy & Training'), ('terms', 'Terms of Service'), ('privacy', 'Privacy Policy'), ('cookies', 'Cookie Policy'), ('shop', 'Shop'), ('foundations', 'Foundations'), ('motto', 'Motto'), ('vision', 'Vision'), ('mission', 'Mission'), ('core-values', 'Core Values')], help_text="Set only for Type='Standing Page'. Fetch pages by this, never by slug.", max_length=20, null=True, unique=True, verbose_name='Page Key'),
        ),
    ]
