# Generated by Django 5.2.15 on 2026-08-21 03:56, hand-edited (2026-08-21):
# graduation_year (IntegerField) -> graduation_date (DateField) needs to
# preserve existing data, not just swap columns -- makemigrations'
# autodetector only offers a plain Remove+Add (order below reflects that
# manual edit: Add, then copy data across, then Remove).

from datetime import date

from django.db import migrations, models


def copy_year_to_date(apps, schema_editor):
    AlumniProfile = apps.get_model('home', 'AlumniProfile')
    for alumni in AlumniProfile.objects.exclude(graduation_year__isnull=True):
        alumni.graduation_date = date(alumni.graduation_year, 1, 1)
        alumni.save(update_fields=['graduation_date'])


def copy_date_to_year(apps, schema_editor):
    # Reverse, for completeness -- collapses back to just the year,
    # same lossy direction the old field always was.
    AlumniProfile = apps.get_model('home', 'AlumniProfile')
    for alumni in AlumniProfile.objects.exclude(graduation_date__isnull=True):
        alumni.graduation_year = alumni.graduation_date.year
        alumni.save(update_fields=['graduation_year'])


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0040_alumniprofile_digital_id_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumniprofile',
            name='graduation_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.RunPython(copy_year_to_date, copy_date_to_year),
        migrations.RemoveField(
            model_name='alumniprofile',
            name='graduation_year',
        ),
    ]
