# Generated by Django 5.2.15 on 2026-08-27 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0041_remove_alumniprofile_graduation_year_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='qualification',
            options={'ordering': ['faculty__faculty_name', 'level', 'name'], 'verbose_name': 'Programme/Course', 'verbose_name_plural': 'Programmes/Courses'},
        ),
    ]
