# Generated by Django 5.2.15 on 2026-09-04 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0042_qualification_verbose_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('mpesa', 'M-Pesa'), ('credit_card', 'Credit/Debit Card'), ('bank_transfer', 'Bank Transfer'), ('legacy_import', 'Legacy Import (backfilled)')], max_length=20),
        ),
    ]
