# Generated by Django 5.2.15 on 2026-09-07 14:21

import apps.home.models
import cloudinary_storage.storage
import django_resized.forms
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0043_alter_payment_payment_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumniprofile',
            name='digital_id_photo',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, help_text='Formal photo for the Alumni Digital ID (badge + PDF). Falls back to the general profile photo if not set or not yet approved.', keep_meta=True, max_length=255, null=True, quality=90, scale=None, size=[800, 800], upload_to='alumni/digital_id_photos/', verbose_name='Alumni Digital ID Photo'),
        ),
        migrations.AlterField(
            model_name='alumniprofile',
            name='qr_code_image',
            field=models.ImageField(blank=True, help_text="Auto-generated QR code linking to this alumnus's profile page.", max_length=255, null=True, upload_to=apps.home.models.alumni_qr_upload_path, verbose_name='QR Code'),
        ),
        migrations.AlterField(
            model_name='article',
            name='article_banner_image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, max_length=255, null=True, quality=85, scale=None, size=[2200, 2200], upload_to='articles/banners/'),
        ),
        migrations.AlterField(
            model_name='article',
            name='thumbnail',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, max_length=255, null=True, quality=85, scale=None, size=[1600, 1600], upload_to='articles/images/'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='affinity_programs_image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, help_text="Homepage 'Affinity programs' card image.", keep_meta=True, max_length=255, null=True, quality=85, scale=None, size=[2200, 2200], upload_to='banner/program_areas/affinity_programs/'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='alumni_qr_watermark',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, help_text='Crest embedded in the center of ALUMNI QR codes. Falls back to the UoNAA crest if unset.', keep_meta=True, max_length=255, null=True, quality=90, scale=None, size=[800, 800], upload_to='banner/alumni_qr_watermark/'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='bottom_banner',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, help_text='Footer background image (templates/snippets/footer.html).', keep_meta=True, max_length=255, null=True, quality=85, scale=None, size=[2200, 2200], upload_to='banner/bottom_banner/'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='career_professional_programs_image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, help_text="Homepage 'Career and professional programs' card image.", keep_meta=True, max_length=255, null=True, quality=85, scale=None, size=[2200, 2200], upload_to='banner/program_areas/career_professional_programs/'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='footer_logo',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, help_text="Footer logo -- usually a white/reversed variant of the main logo, for contrast against the footer's dark background.", keep_meta=True, max_length=255, null=True, quality=90, scale=None, size=[500, 500], upload_to='banner/footer_logo/'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, help_text='Upload banner images ', keep_meta=True, max_length=255, null=True, quality=85, scale=None, size=[2200, 2200], upload_to='banner/image/'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='logo',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, help_text='Site logo -- navbar, top-left (templates/snippets/navbar.html).', keep_meta=True, max_length=255, null=True, quality=90, scale=None, size=[500, 500], upload_to='banner/logo/'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='middle_banner',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, help_text='Upload your item images ', keep_meta=True, max_length=255, null=True, quality=85, scale=None, size=[2200, 2200], upload_to='banner/middle_banner/'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='off_campus_programs_image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, help_text="Homepage 'Off-campus programs' card image.", keep_meta=True, max_length=255, null=True, quality=85, scale=None, size=[2200, 2200], upload_to='banner/program_areas/off_campus_programs/'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='on_campus_programs_image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, help_text="Homepage 'On-campus programs' card image.", keep_meta=True, max_length=255, null=True, quality=85, scale=None, size=[2200, 2200], upload_to='banner/program_areas/on_campus_programs/'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='online_part_time_alumni_image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, help_text="Homepage 'Engagement of alumni of online and part-time degree programs' card image.", keep_meta=True, max_length=255, null=True, quality=85, scale=None, size=[2200, 2200], upload_to='banner/program_areas/online_part_time_alumni/'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='page_background',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, help_text='Background image shown behind the scholarship, profile, and analytics pages.', keep_meta=True, max_length=255, null=True, quality=85, scale=None, size=[2200, 2200], upload_to='banner/page_background/'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='profile_update_card_image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, help_text="Homepage 'Keep Your UoN Alumni Profile Up to Date' card image.", keep_meta=True, max_length=255, null=True, quality=85, scale=None, size=[2200, 2200], upload_to='banner/profile_update_card_image/'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='staff_qr_watermark',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, help_text='Crest embedded in the center of STAFF QR codes. Falls back to the UoN crest if unset.', keep_meta=True, max_length=255, null=True, quality=90, scale=None, size=[800, 800], upload_to='banner/staff_qr_watermark/'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='top_banner',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, help_text='Homepage hero background (templates/snippets/banner.html).', keep_meta=True, max_length=255, null=True, quality=85, scale=None, size=[2200, 2200], upload_to='banner/top_banner/'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='undergraduate_alumni_programs_image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, help_text="Homepage 'Programs for undergraduate students and undergraduate young alumni' card image.", keep_meta=True, max_length=255, null=True, quality=85, scale=None, size=[2200, 2200], upload_to='banner/program_areas/undergraduate_alumni_programs/'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='volunteer_card_image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, help_text="Homepage 'Volunteer and Share Your Experience' card image.", keep_meta=True, max_length=255, null=True, quality=85, scale=None, size=[2200, 2200], upload_to='banner/volunteer_card_image/'),
        ),
        migrations.AlterField(
            model_name='chapter',
            name='thumbnail',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, help_text='Chapter banner ', keep_meta=True, max_length=255, null=True, quality=85, scale=None, size=[1600, 1600], upload_to='chapter/uploads/'),
        ),
        migrations.AlterField(
            model_name='corevalue',
            name='background_image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, help_text='Background image for this core value', keep_meta=True, max_length=255, null=True, quality=85, scale=None, size=[2200, 2200], upload_to='core_values/bg/'),
        ),
        migrations.AlterField(
            model_name='event',
            name='thumbnail',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, max_length=255, null=True, quality=85, scale=None, size=[2200, 2200], upload_to='walk/images/'),
        ),
        migrations.AlterField(
            model_name='executive',
            name='avatar',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, max_length=255, null=True, quality=85, scale=None, size=[1200, 1200], upload_to='gallery/executive/'),
        ),
        migrations.AlterField(
            model_name='images',
            name='image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, help_text='Upload your image ', keep_meta=True, max_length=255, null=True, quality=85, scale=None, size=[2200, 2200], upload_to='gallery/image-uploads'),
        ),
        migrations.AlterField(
            model_name='inmemoriam',
            name='photo',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, max_length=255, null=True, quality=85, scale=None, size=[1200, 1200], upload_to='in_memoriam/'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='thumbnail',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, max_length=255, null=True, quality=85, scale=None, size=[1600, 1600], upload_to='gallery/partners/'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='cover_image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, max_length=255, null=True, quality=85, scale=None, size=[1600, 1600], upload_to='publications/covers/'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='file',
            field=models.FileField(max_length=255, storage=cloudinary_storage.storage.RawMediaCloudinaryStorage, upload_to='publications/'),
        ),
        migrations.AlterField(
            model_name='secretariat',
            name='avatar',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, max_length=255, null=True, quality=85, scale=None, size=[1200, 1200], upload_to='gallery/secretariat/'),
        ),
    ]
