# Generated by Django 5.2.15 on 2026-08-05 18:27

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QRCode',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('label', models.CharField(blank=True, default='', max_length=255)),
                ('token', models.CharField(editable=False, max_length=64, unique=True)),
                ('qr_type', models.CharField(choices=[('ID', 'Main ID Badge'), ('TEMP', 'Temporary Pass'), ('ACCESS', 'Restricted Area Access'), ('VISITOR', 'Visitor Pass'), ('EVENT', 'Event Pass')], default='ID', max_length=10)),
                ('issued_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'QR code',
                'verbose_name_plural': 'QR codes',
            },
        ),
        migrations.CreateModel(
            name='ScanLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scanned_at', models.DateTimeField(auto_now_add=True)),
                ('result', models.CharField(choices=[('VALID', 'Valid'), ('REVOKED', 'Revoked'), ('EXPIRED', 'Expired'), ('BAD_TOKEN', 'Bad token'), ('UNKNOWN', 'Unknown QR id')], max_length=10)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, default='', max_length=255)),
            ],
            options={
                'ordering': ['-scanned_at'],
            },
        ),
        migrations.CreateModel(
            name='Supervisor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'QR Supervisor',
                'verbose_name_plural': 'QR Supervisors',
            },
        ),
    ]
