# Generated by Django 5.2.15 on 2026-08-05 18:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('qr_manager', '0001_initial'),
        ('staff', '0001_initial'),
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='qrcode',
            name='employee',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employee_qrcode', to='staff.employee'),
        ),
        migrations.AddField(
            model_name='scanlog',
            name='qrcode',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scans', to='qr_manager.qrcode'),
        ),
        migrations.AddField(
            model_name='supervisor',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='qr_supervisors', to='home.department'),
        ),
        migrations.AddField(
            model_name='supervisor',
            name='research_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='qr_supervisors', to='staff.researchunit'),
        ),
        migrations.AddField(
            model_name='supervisor',
            name='service_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='qr_supervisors', to='staff.serviceunit'),
        ),
    ]
