# Generated by Django 5.2.15 on 2026-08-14 00:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0029_alumniprofile_qr_code_image'),
        ('qr_manager', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='qrcode',
            name='alumni_profile',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alumni_qrcode', to='home.alumniprofile'),
        ),
    ]
