# Hand-authored, not autogenerated -- Django's own autodetector proposed
# CreateModel for ScholarshipApplication/InterviewScoreSheet here, which
# would DROP AND RECREATE tables that already hold live data in
# apps.home (home_scholarshipapplication / home_interviewscoresheet).
# Restructured into three parts instead:
#   1. Real AddField operations for Student's three genuinely-new columns
#      (alt_phone/county/student_email) -- field definitions copied
#      verbatim from `manage.py makemigrations --dry-run -v 3` output to
#      avoid any hand-transcription error.
#   2. State-only CreateModel for ScholarshipApplication/InterviewScoreSheet,
#      WITHOUT their new student/evaluator fields yet (matching what's
#      actually in the DB right now) -- tells Django's state these models
#      now live in `student`, without touching the tables.
#   3. A real AlterModelTable rename (home_* -> student_*, matching this
#      app's naming convention) plus real AddField for the two genuinely
#      new FK columns (student, evaluator), which don't exist in the DB
#      at all yet and need actual ADD COLUMN operations.
import django.core.validators
import django.db.models.deletion
import phonenumber_field.modelfields
from django.db import migrations, models

_COUNTY_CHOICES = [
    ('mombasa', 'Mombasa'), ('kwale', 'Kwale'), ('kilifi', 'Kilifi'), ('tana_river', 'Tana River'),
    ('lamu', 'Lamu'), ('taita_taveta', 'Taita-Taveta'), ('garissa', 'Garissa'), ('wajir', 'Wajir'),
    ('mandera', 'Mandera'), ('marsabit', 'Marsabit'), ('isiolo', 'Isiolo'), ('meru', 'Meru'),
    ('tharaka_nithi', 'Tharaka-Nithi'), ('embu', 'Embu'), ('kitui', 'Kitui'), ('machakos', 'Machakos'),
    ('makueni', 'Makueni'), ('nyandarua', 'Nyandarua'), ('nyeri', 'Nyeri'), ('kirinyaga', 'Kirinyaga'),
    ('muranga', "Murang'a"), ('kiambu', 'Kiambu'), ('turkana', 'Turkana'), ('west_pokot', 'West Pokot'),
    ('samburu', 'Samburu'), ('trans_nzoia', 'Trans Nzoia'), ('uasin_gishu', 'Uasin Gishu'),
    ('elgeyo_marakwet', 'Elgeyo-Marakwet'), ('nandi', 'Nandi'), ('baringo', 'Baringo'), ('laikipia', 'Laikipia'),
    ('nakuru', 'Nakuru'), ('narok', 'Narok'), ('kajiado', 'Kajiado'), ('kericho', 'Kericho'),
    ('bomet', 'Bomet'), ('kakamega', 'Kakamega'), ('vihiga', 'Vihiga'), ('bungoma', 'Bungoma'),
    ('busia', 'Busia'), ('siaya', 'Siaya'), ('kisumu', 'Kisumu'), ('homa_bay', 'Homa Bay'),
    ('migori', 'Migori'), ('kisii', 'Kisii'), ('nyamira', 'Nyamira'), ('nairobi', 'Nairobi City'),
]


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0026_move_scholarship_models_to_student'),
        ('staff', '0002_initial'),
        ('student', '0001_initial'),
    ]

    operations = [
        # ---- 1. Genuinely new Student columns (real, both state + DB) ----
        migrations.AddField(
            model_name='student',
            name='alt_phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region='KE'),
        ),
        migrations.AddField(
            model_name='student',
            name='county',
            field=models.CharField(blank=True, choices=_COUNTY_CHOICES, max_length=32, verbose_name='County of residence'),
        ),
        migrations.AddField(
            model_name='student',
            name='student_email',
            field=models.EmailField(blank=True, help_text='The university-issued @students.uonbi.ac.ke address.', max_length=254, verbose_name='Student (university) email'),
        ),

        # ---- 2. State-only: these tables already exist under apps.home,
        #         renamed below -- not recreated. Fields exactly as they
        #         are in the DB right now, i.e. WITHOUT student/evaluator. ----
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.CreateModel(
                    name='ScholarshipApplication',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('submitted_at', models.DateTimeField(auto_now_add=True, verbose_name='Timestamp')),
                        ('first_name', models.CharField(max_length=100, verbose_name='First/Baptismal')),
                        ('middle_name', models.CharField(blank=True, max_length=100)),
                        ('surname', models.CharField(max_length=100, verbose_name='Surname/Family Name')),
                        ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=10)),
                        ('date_of_birth', models.DateField()),
                        ('registration_number', models.CharField(max_length=30, unique=True, verbose_name='University registration number')),
                        ('current_course', models.CharField(max_length=150)),
                        ('year_of_study', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(7)])),
                        ('mobile_no', models.CharField(max_length=20, verbose_name='Tel./Mobile No')),
                        ('alternative_mobile_no', models.CharField(blank=True, max_length=20)),
                        ('email', models.EmailField(max_length=254)),
                        ('county_of_residence', models.CharField(choices=_COUNTY_CHOICES, max_length=100)),
                        ('sub_county', models.CharField(max_length=100)),
                        ('ward', models.CharField(max_length=100)),
                        ('location', models.CharField(max_length=100)),
                        ('sub_location', models.CharField(max_length=100)),
                        ('school_name', models.CharField(max_length=200)),
                        ('kcse_grade', models.CharField(choices=[('A', 'A'), ('A-', 'A-'), ('B+', 'B+'), ('B', 'B'), ('B-', 'B-'), ('C+', 'C+'), ('C', 'C'), ('C-', 'C-'), ('D+', 'D+'), ('D', 'D'), ('D-', 'D-'), ('E', 'E')], max_length=5, verbose_name='KCSE Grade')),
                        ('kcse_year', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1985), django.core.validators.MaxValueValidator(2026)])),
                        ('school_phone_no', models.CharField(blank=True, max_length=20)),
                        ('head_teacher_no', models.CharField(blank=True, max_length=20)),
                        ('school_county', models.CharField(max_length=100)),
                        ('other_achievement_1', models.TextField(blank=True, verbose_name='State any other academic achievement')),
                        ('other_achievement_2', models.TextField(blank=True)),
                        ('physical_copy', models.FileField(upload_to='scholarship_applications/%Y/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'jpg', 'jpeg', 'png'])])),
                        ('academic_level', models.CharField(choices=[('undergraduate', 'Undergraduate'), ('postgraduate', 'Postgraduate')], default='undergraduate', max_length=20)),
                        ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='scholarship_applications', to='home.department')),
                        ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='scholarship_applications', to='home.faculty')),
                    ],
                    options={
                        'verbose_name': 'Scholarship Application',
                        'ordering': ['-submitted_at'],
                        'db_table': 'home_scholarshipapplication',
                    },
                ),
                migrations.CreateModel(
                    name='InterviewScoreSheet',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('venue', models.CharField(default='Alumni Offices', max_length=150)),
                        ('interview_date', models.DateField()),
                        ('time_start', models.TimeField()),
                        ('time_stop', models.TimeField()),
                        ('course_undertaking', models.CharField(max_length=150)),
                        ('score_about_yourself', models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(5)])),
                        ('score_socioeconomic', models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(10)])),
                        ('score_previous_education', models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(5)])),
                        ('score_strength_weakness', models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(5)])),
                        ('score_deserve_scholarship', models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(10)])),
                        ('score_role_model', models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(5)])),
                        ('score_family_status', models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(5)])),
                        ('score_personality', models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(5)])),
                        ('parental_status', models.CharField(choices=[('orphan', 'Orphan'), ('one_parent', 'One Parent'), ('both_parents', 'Both Parents')], max_length=15)),
                        ('received_other_funding', models.BooleanField(verbose_name='Have you received other funding...')),
                        ('verdict', models.IntegerField(choices=[(1, 'Qualifies for scholarship award'), (2, 'Does not qualify for scholarship award')])),
                        ('prepared_by_name', models.CharField(max_length=150)),
                        ('prepared_by_signature', models.CharField(blank=True, max_length=150)),
                        ('other_remarks', models.TextField(blank=True)),
                        ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='score_sheet', to='student.scholarshipapplication')),
                    ],
                    options={
                        'verbose_name': 'Interview Score Sheet',
                        'db_table': 'home_interviewscoresheet',
                    },
                ),
            ],
            database_operations=[],
        ),

        # ---- 3. Real: rename the physical tables to match this app,
        #         then add the two genuinely new FK columns. ----
        migrations.AlterModelTable(
            name='scholarshipapplication',
            table='student_scholarshipapplication',
        ),
        migrations.AlterModelTable(
            name='interviewscoresheet',
            table='student_interviewscoresheet',
        ),
        migrations.AddField(
            model_name='scholarshipapplication',
            name='student',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='applicant', to='student.student'),
        ),
        migrations.AddField(
            model_name='interviewscoresheet',
            name='evaluator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='evaluations', to='staff.employee'),
        ),
    ]
