# Generated by Django 5.2.15 on 2026-08-13 23:34

import apps.student.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_move_scholarship_models_from_home'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scholarshipapplication',
            name='physical_copy',
            field=models.FileField(upload_to=apps.student.models._scholarship_physical_copy_path, validators=[django.core.validators.FileExtensionValidator(['pdf'])]),
        ),
    ]
