# Generated by Django 5.2.15 on 2026-09-07 14:21

import apps.student.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_alter_scholarshipapplication_physical_copy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scholarshipapplication',
            name='physical_copy',
            field=models.FileField(max_length=255, upload_to=apps.student.models._scholarship_physical_copy_path, validators=[django.core.validators.FileExtensionValidator(['pdf'])]),
        ),
    ]
